/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper */

#ifndef _Included_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
#define _Included_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    cache_Java_objects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_cache_1Java_1objects
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    init_asset_manager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_init_1asset_1manager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    set_current_language
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_set_1current_1language
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_num_languages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1num_1languages
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_language_code
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1language_1code
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_language_endonym
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1language_1endonym
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    is_current_language_index
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_is_1current_1language_1index
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    is_current_language_code
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_is_1current_1language_1code
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_current_two_letter_language_code
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1current_1two_1letter_1language_1code
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    current_language_reads_left_to_right
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_current_1language_1reads_1left_1to_1right
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    current_language_reads_right_to_left
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_current_1language_1reads_1right_1to_1left
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_localized_text_as_java_string
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1localized_1text_1as_1java_1string
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    adjust_key_for_number
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_adjust_1key_1for_1number
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    alloc_model_data
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_alloc_1model_1data
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    free_model_data
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_free_1model_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    set_up_model_data
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_set_1up_1model_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    shut_down_model_data
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_shut_1down_1model_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    alloc_graphics_data_gl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_alloc_1graphics_1data_1gl
  (JNIEnv *, jclass);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    free_graphics_data_gl
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_free_1graphics_1data_1gl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    zero_graphics_data_gl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_zero_1graphics_1data_1gl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    on_draw_frame
 * Signature: (JJIID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jdouble);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    simulation_wants_update
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_simulation_1wants_1update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper
 * Method:    get_and_clear_generic_error_message
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_geometrygames_geometrygamesshared_GeometryGamesJNIWrapper_get_1and_1clear_1generic_1error_1message
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
